[package]
name = "burn-image-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
burn.workspace = true
burn-image-core.workspace = true
bytemuck.workspace = true
half.workspace = true
memmap2.workspace = true
safetensors.workspace = true
thiserror.workspace = true
