[package]
name = "burn-models-clip"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
burn.workspace = true
burn-models-core.workspace = true
regex.workspace = true
thiserror.workspace = true
